name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run : export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH && ./main
    
  build_centos-stream-8:
    runs-on: ubuntu-latest
    container: 'quay.io/centos/centos:stream8'
    steps:
    - uses: actions/checkout@v2
    - name: prerequisits
      run: yum install -y git make gcc-c++ zlib-devel dialog
    - name: make
      run: make
    - name: test
      run : export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH && ./main

  build_centos-7:
    runs-on: ubuntu-latest
    container: 'centos:centos7'
    steps:
    - uses: actions/checkout@v2
    - name: prerequisits
      run: yum install -y git make gcc-c++ zlib-devel dialog
    - name: make
      run: make
    - name: test
      run : export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH && ./main
